### ISSUE TITLE
Cant download vagrant box

### ISSUE THREAD

**Issue by biocyberman** [broadinstitute/viral-ngs#577] opened 2017-02-11 02:08 UTC
I am trying to setup vagrant box for viral-ngs. This is what I currently get, tried both with login and without login to Atlas.

```
vagrant up --provider virtualbox
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'ubuntu/vivid64' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
The box 'ubuntu/vivid64' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Atlas, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://atlas.hashicorp.com/ubuntu/vivid64"]
Error: The requested URL returned error: 404 Not Found

```

**Comment by biocyberman** [comment] 2017-02-12 20:58
I changed to `ubuntu/xenial64` and got some progress with this. However, there are still many small glitches before and can run smoothly with this.

**Comment by tomkinsc** [comment] 2017-02-14 15:10
It looks like Hashicorp may have removed Ubuntu 15.04 (vivid); that's unfortunate for reproducibility. 

At this point, deployment-related files have moved to a separate repository: https://github.com/broadinstitute/viral-ngs-deploy

The Ansible deployment files predate our conda package and Docker [container](https://hub.docker.com/r/broadinstitute/viral-ngs/tags/), so I just opened a PR (#579) to remove them from this repository. They're somewhat deprecated at this point, though they still exist in [viral-ngs-deploy](https://github.com/broadinstitute/viral-ngs-deploy). I'll have to look into updating them.

I'd encourage you to give the Docker container a try, or to install the conda package for local use or development of viral-ngs.

**Comment by tomkinsc** [comment] 2017-02-14 15:11
Closing this for now, deployment-related issues should ideally be directed to https://github.com/broadinstitute/viral-ngs-deploy.

**Closed** 2017-02-14 15:10 UTC

**Comment by biocyberman** [comment] 2017-02-14 19:09
Thanks for the updates. I will try the docker container.
